/*
	Mod Support
	Authors: Chrisy15
*/

-----------------------------------------------
-- Rule with Faith
-----------------------------------------------

INSERT INTO Civilization_Titles
		(CivilizationType, 			GovernmentType, 							PolicyType,				LeaderTitle															)
VALUES	('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_CHIEFDOM',						NULL,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_HORDE',						NULL,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_AKKAD'					),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_POLIS',						NULL,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_AKKAD'					),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_AUTOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_OLIGARCHY',						NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_AKKAD'				), 
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_CLASSICAL_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_AKKAD'		),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_MONARCHY',						NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_THEOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_THEOCRACY_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_MERCHANT_REPUBLIC',				NULL,					'LOC_GOVERNMENT_JFD_REPUBLIC_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_REPUBLIC_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_DEMOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_AKKAD'		),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_COMMUNISM',						NULL,					'LOC_GOVERNMENT_JFD_REPUBLIC_LEADER_TITLE_CVS_AKKAD'				),
		('CIVILIZATION_CVS_AKKAD',	'GOVERNMENT_FASCISM',						NULL,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_AKKAD'					);

DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_AKKAD' AND GovernmentType IS NOT NULL AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_AKKAD' AND PolicyType IS NOT NULL AND PolicyType NOT IN (SELECT PolicyType FROM Policies);

-----------------------------------------------
-- Colonial City Names
-----------------------------------------------

CREATE TABLE IF NOT EXISTS C15_ColonyCityNames (CivilizationType TEXT NOT NULL, LeaderType TEXT DEFAULT NULL, CityName TEXT NOT NULL, PRIMARY KEY (CivilizationType, LeaderType, CityName));

CREATE TRIGGER IF NOT EXISTS C15_ColonyCityNames_RemoveFromCityNames
AFTER INSERT ON C15_ColonyCityNames
BEGIN
	DELETE FROM CityNames WHERE CityName = NEW.CityName AND (CivilizationType = NEW.CivilizationType OR LeaderType = NEW.LeaderType);
END;

CREATE TRIGGER IF NOT EXISTS C15_ColonyCityNames_DupeAddedToCityNames
AFTER INSERT ON CityNames
WHEN NEW.CityName IN (SELECT CityName FROM C15_ColonyCityNames WHERE CivilizationType = NEW.CivilizationType)
BEGIN
	DELETE FROM CityNames WHERE CityName = NEW.CityName AND CivilizationType = NEW.CivilizationType;
END;

INSERT OR REPLACE INTO C15_ColonyCityNames
		(CivilizationType,				CityName)
SELECT	'CIVILIZATION_CVS_AKKAD',		CityName
FROM C15_ColonyCityNames WHERE CivilizationType = 'CIVILIZATION_SUMERIA';

CREATE TRIGGER IF NOT EXISTS CVS_Akkad_CCNStealSumer
AFTER INSERT ON C15_ColonyCityNames
WHEN NEW.CivilizationType = 'CIVILIZATION_SUMERIA'
BEGIN
	INSERT OR REPLACE INTO C15_ColonyCityNames
			(CivilizationType,				CityName)
	VALUES	('CIVILIZATION_CVS_AKKAD',		NEW.CityName);
END;